services:
  - type: web
    name: chat-app-spring
    runtime: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/chat-backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false