spring:
  application:
    name: chat-backend

  data:
    mongodb:
      uri: mongodb+srv://vivekparde2411:HP0BfZbyK42nKQRZ@cluster0.rwqnq5h.mongodb.net/chat-application

server:
  port: ${PORT:8080}

jwt:
  secret: myVeryLongSecretKeyForChatApp123456
  expiration: 1296000000 # 15 days in milliseconds