spring:
  application:
    name: chat-backend

  data:
    mongodb:
#      uri: mongodb+srv://vivekparde2411:HP0BfZbyK42nKQRZ@cluster0.rwqnq5h.mongodb.net/chat-application
      uri: ${MONGODB_URI}

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  expiration: 1296000000 # 15 days in milliseconds